spring:
  application:
    name: cms
  datasource:
    url: jdbc:mysql://localhost:3306/cms?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  servlet:
    contextPath: /api
  port: 8081
  
